New configure script to determine fubar'd gmp libraries / search paths
git-svn-id: svn+ssh://localhost/home/epiphani/home/dalrepo/bahamut/trunk@428 57140981-5af7-11db-9af8-080020d9fdd4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2489,15 +2489,16 @@ if test "$GMPLIB" = ""; then
   echo "You can download gmp at http://www.swox.com/gmp, or any of the"
   echo "GNU distribution sites (http://www.gnu.org for more information)"
   exit 1
-else
-  echo Checking $GMPINC/$GMPINCFN directory for gmp version
-  echo $ac_n "checking for gmp version""... $ac_c" 1>&6
-echo "configure:2496: checking for gmp version" >&5
+fi
+
+echo Checking $GMPINC/$GMPINCFN directory for gmp version
+echo $ac_n "checking for gmp.h version""... $ac_c" 1>&6
+echo "configure:2497: checking for gmp.h version" >&5
 if test "$cross_compiling" = yes; then
   echo "$ac_t""can't tell" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2501 "configure"
+#line 2502 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -2512,28 +2513,41 @@ int main()
 }
 
 EOF
-if { (eval echo configure:2516: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2517: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   echo "$ac_t""ok" 1>&6
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -fr conftest*
-  echo "$ac_t""too old" 1>&6
-{ echo "configure: error: Invalid or too old gmp.h" 1>&2; exit 1; }
+  
+echo "$ac_t""too old" 1>&6
+echo "I found a version of gmp.h, but it was either not the gmp I know of,"
+echo "or it was not recent enough (I need gmp version 3.0 or later!)"
+echo ""
+echo "You should upgrade gmp from the URL below."
+echo ""
+echo "If you do not want to upgrade gmp system wide:"
+echo "You may make a directory \"gmp\" in the current directory"
+echo "and place libgmp.a and gmp.h in that directory, and I will"
+echo "autodetect it next time you run configure."
+echo ""
+echo "You can download gmp at http://www.swox.com/gmp, or any of the"
+echo "GNU distribution sites (http://www.gnu.org for more information)"
+{ echo "configure: error: Invalid or too old gmp.h (pre-version 3?)" 1>&2; exit 1; }
+
 fi
 rm -fr conftest*
 fi
 
-fi # option 
 
 echo $ac_n "checking how to link to the gmp library""... $ac_c" 1>&6
-echo "configure:2532: checking how to link to the gmp library" >&5
+echo "configure:2546: checking how to link to the gmp library" >&5
 if test "$cross_compiling" = yes; then
   echo "$ac_t""grr cross compiler blah!" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2537 "configure"
+#line 2551 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -2554,7 +2568,7 @@ int main()
 
 
 EOF
-if { (eval echo configure:2558: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2572: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   
 echo "$ac_t""dynamic" 1>&6
@@ -2574,6 +2588,165 @@ rm -fr conftest*
 fi
 
 
+BKLIBS="$LIBS"
+LIBS="$LIBS $GMP_LIBS"
+
+echo $ac_n "checking for gmp library matching with header""... $ac_c" 1>&6
+echo "configure:2596: checking for gmp library matching with header" >&5
+if test "$cross_compiling" = yes; then
+  echo "$ac_t""cross compile" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 2601 "configure"
+#include "confdefs.h"
+
+#include <stdio.h>
+#include <stdlib.h>
+#include "$GMPINC/$GMPINCFN"
+
+extern const char *gmp_version;
+
+char *str_next_period(char *x)
+{
+   while(*x && *x != '.')
+      x++;
+
+   if(*x)
+   {
+      *x = '\0';
+      return x + 1;
+   }
+
+   return NULL;
+}
+
+void *my_lame_strcpy(char *x, char *y, int ml)
+{
+   while(*x && ml--)
+   {
+      *x++ = *y++;
+   }
+   *x = '\0';
+}
+
+int main()
+{
+  int major_h = 0;
+  int minor_h = 0;
+  int plevel_h = 0;
+  int major_l = 0;
+  int minor_l = 0;
+  int plevel_l = 0;
+  char gv[128], *x, *z;
+  FILE *fp;
+
+  my_lame_strcpy(gv, gmp_version, 128);
+
+#ifdef __GNU_MP_VERSION
+  major_h = __GNU_MP_VERSION;
+#endif
+#ifdef __GNU_MP_VERSION_MINOR
+  minor_h = __GNU_MP_VERSION_MINOR;
+#endif
+#ifdef __GNU_MP_VERSION_PATCHLEVEL
+  plevel_h = __GNU_MP_VERSION_PATCHLEVEL;
+#endif
+
+  fp = fopen(".gmp_h_version", "w");
+  if(fp)
+  {
+     fprintf(fp, "%d.%d.%d", major_h, minor_h, plevel_h);
+     fclose(fp);
+  }
+
+  z = gv;
+  x = str_next_period(z);
+  major_l = atoi(z);
+  if(x)
+  {
+     z = x;
+     x = str_next_period(z);
+     minor_l = atoi(z);
+     if(x)
+     {
+        z = x;
+        x = str_next_period(z);
+        plevel_l = atoi(z);
+     }
+  }
+
+  fp = fopen(".gmp_l_version", "w");
+  if(fp)
+  {
+     fprintf(fp, "%d.%d.%d", major_l, minor_l, plevel_l);
+     fclose(fp);
+  }
+
+  if(major_l != major_h)
+     exit(1);
+
+  exit(0);
+}
+
+EOF
+if { (eval echo configure:2693: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  
+echo "$ac_t""no problems" 1>&6
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  
+echo "$ac_t""problem!" 1>&6
+echo "Your gmp library either has no version symbols, is not the correct 'gmp',"
+echo "or the major versions of your gmp library and gmp header differ."
+echo "You cannot have two versions of the gmp library in your dynamic (.so)"
+echo "library search path, this may be your problem."
+echo ""
+echo "You should upgrade gmp from the URL below."
+echo ""
+echo "If you do not want to upgrade gmp system wide:"
+echo "You may make a directory \"gmp\" in the current directory"
+echo "and place libgmp.a and gmp.h in that directory, and I will"
+echo "autodetect it next time you run configure."
+echo ""
+echo "You can download gmp at http://www.swox.com/gmp, or any of the"
+echo "GNU distribution sites (http://www.gnu.org for more information)"
+{ echo "configure: error: "bad library/header match"" 1>&2; exit 1; }
+
+fi
+rm -fr conftest*
+fi
+
+
+LIBS="$BKLIBS"
+
+GMPHV=`cat .gmp_h_version`
+GMPLV=`cat .gmp_l_version`
+echo " - gmp header version: $GMPHV"
+echo " - gmp library version: $GMPLV"
+$RM -f .gmp_h_version .gmp_l_version
+
+if test "$GMPHV" != "$GMPLV"; then
+   echo ""
+   echo "Warning!"
+   echo "Your gmp.h and gmp library versions seem to differ!"
+   echo "If you get any linking errors regarding gmp functions (mpz_*),"
+   echo "this is probably the source of your problem!"
+   echo ""
+   echo "You can upgrade gmp from the URL below."
+   echo ""
+   echo "If you do not want to upgrade gmp system wide:"
+   echo "You may make a directory \"gmp\" in the current directory"
+   echo "and place libgmp.a and gmp.h in that directory, and I will"
+   echo "autodetect it next time you run configure."
+   echo ""
+   echo "You can download gmp at http://www.swox.com/gmp, or any of the"
+   echo "GNU distribution sites (http://www.gnu.org for more information)"
+fi
+
    
    
    
@@ -2581,7 +2754,7 @@ fi
 fi
 
 echo $ac_n "checking operating system""... $ac_c" 1>&6
-echo "configure:2585: checking operating system" >&5
+echo "configure:2758: checking operating system" >&5
 case "$target" in
 *-solaris2*) cat >> confdefs.h <<\EOF
 #define OS_SOLARIS2 1
